Repository dsgibbons/shap, pull requests merged in 2023-05, with the labels that each got.

#34 docs: typo fixes
  notebooks/overviews/An introduction to explainable AI with Shapley values.ipynb
Labels: documentation

#36 fix: change sampling to without replacement
  shap/utils/_general.py
  tests/utils/test_general.py
Labels: bug

#45 chore: add tensorflow to tests optional dependencies
  .github/workflows/run_tests.yml
  setup.py
Labels: ci

#77 Fix failing test from incorrect comparison of bools and ints
  shap/explainers/_exact.py
Labels: bug

#68 Fix further NumbaDeprecationWarnings: migrate from jit to njit
  shap/explainers/_exact.py
  shap/explainers/_partition.py
  shap/links.py
  shap/maskers/_image.py
  shap/maskers/_tabular.py
  shap/utils/_clustering.py
  shap/utils/_masked_model.py
Labels: bug

#75 Fix further test suite warnings and deprecations
  shap/benchmark/models.py
  shap/explainers/_gradient.py
  shap/explainers/_kernel.py
  tests/explainers/test_linear.py
  tests/explainers/test_tree.py
Labels: bug, ci

#81 Fix: Allow minor variations in random_summary plot
  tests/plots/test_summary.py
Labels: bug

#72 Add support for python 3.11
  .github/workflows/run_tests.yml
  setup.py
Labels: enhancement, ci

#91 ci: only run tests when src code changes
  .github/workflows/run_tests.yml
Labels: ci

#86 fix: Explanation hstack undefined name error
  shap/_explanation.py
  tests/test_explanation.py
Labels: bug

#87 fix: violin plots tests
  shap/plots/_beeswarm.py
  shap/plots/_violin.py
  tests/plots/baseline/test_random_summary_layered_violin_with_data.png
  tests/plots/test_summary.py
  tests/plots/test_violin.py
Labels: bug

#88 fix: lightgbm call with categoricals bug
  CHANGELOG.md
  shap/explainers/_tree.py
  tests/explainers/test_tree.py
Labels: bug
